export type ActiveView = 'inventory' | 'maintenance' | 'settings' | 'cases' | 'alerts'
export type AuthState = 'checking' | 'authenticated' | 'guest' | 'submitting'
export type LifeSheetState = 'idle' | 'loading' | 'ready' | 'error'
export type LoadState = 'loading' | 'ready' | 'error'
export type ModuleState = 'loading' | 'ready' | 'error'
export type ThemeMode = 'dark' | 'light'
